### GENERAL SETTINGS ###

# Site settings
title: "Singularity Builders"
description: "Static API to serve Singularity Builder Configs"
baseurl: "/builders" #important: start with /
domain: "https://singularityhub.github.io/builders"


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#159958"
  primary_rgb: "21,153,88" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#F7F7F7"
  link: "#159958"
  link_hover: "#01b2fe"
  footer_heading: "#777"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  cloud:
    output: true
    permalink: /cloud/:path

repo: "https://www.github.com/singularityhub/builders"
future: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "bundle"

  -
    scope:
      path: "cloud"
      type: "cloud"
    values:
      layout: "bundle"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://www.twitter.com/containertools

twitter: containertools
